### ISSUE TITLE
Error QrCode generate - PHP8 (Index invalid or out of range)

### ISSUE THREAD

**Issue by MarceloMelo1** [Bacon/BaconQrCode#92]
![image](https://user-images.githubusercontent.com/10995789/133982406-ed4fe014-f3f9-4d44-ba7e-3c8deb4d0b11.png)

**Comment by PhoenixBWS** [comment]
This issue also prevents us from using _endroid/qr-code_. Following error takes over:

**Fatal error**: Uncaught RuntimeException: Index invalid or out of range in <LONG_PATH_TO_DIRECTORY>/public_html/vendor/bacon/bacon-qr-code/src/Encoder/MaskUtil.php:106 Stack trace: #0 <LONG_PATH_TO_DIRECTORY>/public_html/vendor/bacon/bacon-qr-code/src/Encoder/Encoder.php(181): BaconQrCode\Encoder\MaskUtil::applyMaskPenaltyRule3() #1 <LONG_PATH_TO_DIRECTORY>/public_html/vendor/bacon/bacon-qr-code/src/Encoder/Encoder.php(228): BaconQrCode\Encoder\Encoder::calculateMaskPenalty() #2 <LONG_PATH_TO_DIRECTORY>/public_html/vendor/bacon/bacon-qr-code/src/Encoder/Encoder.php(119): BaconQrCode\Encoder\Encoder::chooseMaskPattern() #3 <LONG_PATH_TO_DIRECTORY>/public_html/vendor/endroid/qr-code/src/Bacon/MatrixFactory.php(18): BaconQrCode\Encoder\Encoder::encode() #4 <LONG_PATH_TO_DIRECTORY>/public_html/vendor/endroid/qr-code/src/Writer/PngWriter.php(29): Endroid\QrCode\Bacon\MatrixFactory->create() #5 <LONG_PATH_TO_DIRECTORY>/public_html/components/generator.php(27): Endroid\QrCode\Writer\PngWriter->write() #6 <LONG_PATH_TO_DIRECTORY>/public_html/index.php(27): include('...') #7 **{main} thrown in <LONG_PATH_TO_DIRECTORY>/public_html/vendor/bacon/bacon-qr-code/src/Encoder/MaskUtil.php on line 106**

**Comment by endroid** [comment]
Hi @DASPRiD by any chance do you have the time to look at this issue?

**Comment by DASPRiD** [comment]
> Hi @DASPRiD by any chance do you have the time to look at this issue?

I just performed some cleanup and also migrated tests to Github actions, adding an integration test and adding PHP 8.0 and 8.1 to the test matrix. So far, all the tests are passing:

https://github.com/Bacon/BaconQrCode/actions/runs/1770110321

Could you supply a failing test case?

**Comment by endroid** [comment]
@DASPRiD Thank you. On my side all tests turn green too, however some users reported the same problem in a short time span. I also asked for their specific implementation in https://github.com/endroid/qr-code/issues/365 but their code also turns green in tests. In other words: no failing test case ;)  Strangely enough some users have recently reported that the issue has disappeared on their side. Do you have any clue? I'm out of ideas.

**Comment by acelaya** [comment]
Is this matrix thing in any way related with the time it's generated? Maybe timezones or dates?

**Comment by DASPRiD** [comment]
@acelaya No, there's nothing time related in this library.

@endroid That is extremely weird. I have no idea what could have caused it for them, really. I read through your linked issue and to be honest, it doesn't really make sense. 

Looking at the `MaskUtil` class, the only reason that error could ever happen would be if `ByteMatrix` would report a different width and height than the byte array it contains. But that doesn't make any sense, since the byte array is internally created based on the width and height parameters. It is even more confusing that this is only happening for some people, and only on PHP 8.0/8.1.

Since bot your and my tests don't have any issues (I also tried to create a test case based on the issue on your repo), may I recommend the following to our users:

When you run into the issue, please edit the `MaskUtil.php` file in your vendor folder, and `var_dump()` the `$array`, `$width` and `$height` variables in the `applyMaskPenaltyRule3` method, post the output on gist and link it here. That might give me some lead on the culprit.

**Comment by DASPRiD** [comment]
@gidbrn Oh, really nice find!

I'd say yes, this is most likely a PHP bug, you might want to report it to them :)

**Comment by endroid** [comment]
@gidbrn good job, this issue was really difficult to trace.

**Comment by endroid** [comment]
@hbernaciak Good idea. I personally currently don't have the time to debug and report opcache issue, so go ahead if you like!

**Comment by kyosheek** [comment]
Ran into same issue with `jit = tracing` today. Although everything was fine for like a month after installing and using package.

**Comment by danog** [comment]
A bugfix has been merged upstream in php-src, and will be available in PHP 8.3, 8.2.12 and 8.1.25.

**Comment by DASPRiD** [comment]
Perfect, gonna close the issue then, thanks for the information :)
